Install nginx if KIBANA_USER and KIBANA_PASSWORD are defined

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -86,6 +86,43 @@ if [ -f "$BUILD_DIR/kibana-plugins" ] ; then
   cd $BUILD_DIR
 fi
 
+if [[ -n "$KIBANA_USER" && -n "$KIBANA_PASSWORD" ]] ; then
+  echo "-----> 'KIABANA_PASSWORD detected, installing reverse proxy for authentication"
+  $mkdir /app/vendor/nginx
+  NGINX_VERSION="${NGINX_VERSION:-1.10.1}"
+  NGINX_URL="https://storage.sbg1.cloud.ovh.net/v1/AUTH_be65d32d71a6435589a419eac98613f2/scalingo-php-buildpack/package/nginx-${NGINX_VERSION}.tgz"
+  curl --fail --retry 3 --retry-delay 2 --connect-timeout 3 --max-time 30 -s "$NGINX_URL" | tar -C "$BUILD_DIR/vendor/nginx" -xzf -
+  printf "$KIBANA_USER:$(openssl passwd -1 -salt $(openssl rand -base64 6) $KIBANA_PASSWORD)" > $BUILD_DIR/.kibana-password
+  mv "${KIBANA_DIR}/bin/kibana" "${KIBANA_DIR}/bin/kibana.orig"
+  cp "$basedir/../config/nginx.conf.erb" "$BUILD_DIR/vendor/nginx/conf/nginx.conf.erb"
+  cat > "$KIBANA_DIR/bin/kibana" <<SH
+#!/usr/bin/env bash
+
+basedir="\$( cd -P "\$(dirname \$(dirname "\$0" ))" && pwd )"
+pmsgr=/tmp/pmsgr
+rm -f \$pmsgr
+mkfifo \$pmsgr
+
+erb "\$basedir/vendor/nginx/conf/nginx.conf.erb" > "\$basedir/vendor/nginx/conf/nginx.conf"
+
+(
+    nginx -p "\$basedir/vendor/nginx" -c "\$basedir/vendor/nginx/conf/nginx.conf"
+    echo "nginx" > \$pmsgr
+) &
+
+(
+    nginx -p "\$basedir/${KIBANA_DIR}/bin/kibana.orig" --port 8000
+    echo "kibana" > \$pmsgr
+) &
+
+read exitproc <\$pmsgr
+echo "Boot failed: \$exitproc"
+exit 1
+SH
+
+  chmod +x "{$KIBANA_DIR}/bin/kibana"
+fi
+
 echo "Exporting PATH" | indent
 
 cat <<EOF > $INIT_SCRIPT
